# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"stochastically_convert_to_binary": "01_basics_v2.ipynb",
         "create_nxgraph": "00_basics.ipynb",
         "create_linear_dataset": "00_basics.ipynb",
         "get_feature_importance": "01_basics_v2.ipynb",
         "partial_dependence": "00_basics.ipynb",
         "plot_partial_dependency": "00_basics.ipynb",
         "GenVars": "01_basics_v2.ipynb",
         "CommonCauses": "01_basics_v2.ipynb",
         "Instruments": "01_basics_v2.ipynb",
         "EffectModifiers": "01_basics_v2.ipynb",
         "Treatments": "01_basics_v2.ipynb",
         "initialize": "01_basics_v2.ipynb",
         "generate": "01_basics_v2.ipynb",
         "get_obs": "01_basics_v2.ipynb",
         "CommonCauses.initialize": "01_basics_v2.ipynb",
         "CommonCauses.generate": "01_basics_v2.ipynb",
         "CommonCauses.get_obs": "01_basics_v2.ipynb",
         "Instruments.initialize": "01_basics_v2.ipynb",
         "Instruments.get_obs": "01_basics_v2.ipynb",
         "Instruments.generate": "01_basics_v2.ipynb",
         "EffectModifiers.initialize": "01_basics_v2.ipynb",
         "EffectModifiers.get_obs": "01_basics_v2.ipynb",
         "EffectModifiers.generate": "01_basics_v2.ipynb",
         "Treatments.initialize": "01_basics_v2.ipynb",
         "Treatments.generate": "01_basics_v2.ipynb",
         "Treatments.get_obs": "01_basics_v2.ipynb",
         "Outcomes": "01_basics_v2.ipynb",
         "plot_target_vs_rest": "01_basics_v2.ipynb",
         "plot_var_hists": "01_basics_v2.ipynb",
         "show_correlations": "01_basics_v2.ipynb",
         "get_Xy": "01_basics_v2.ipynb",
         "get_model_feel": "01_basics_v2.ipynb",
         "get_partial_dependencies": "01_basics_v2.ipynb",
         "plot_partial_dependencies": "01_basics_v2.ipynb",
         "GraphGenerator": "01_basics_v2.ipynb",
         "get_only_Xi_to_Y": "01_basics_v2.ipynb",
         "GraphGenerator.get_only_Xi_to_Y": "01_basics_v2.ipynb",
         "vis_g": "01_basics_v2.ipynb",
         "GraphGenerator.vis_g": "01_basics_v2.ipynb",
         "get_gml": "01_basics_v2.ipynb",
         "GraphGenerator.get_gml": "01_basics_v2.ipynb"}

modules = ["basics.py",
           "basics_v2.py"]

doc_url = "https://fastai.github.io/bcg/"

git_url = "https://github.com/fastai/bcg/tree/master/"

def custom_doc_links(name): return None
