# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GenVars": "00_basics.ipynb",
         "CommonCauses": "00_basics.ipynb",
         "Instruments": "00_basics.ipynb",
         "EffectModifiers": "00_basics.ipynb",
         "Treatments": "00_basics.ipynb",
         "initialize": "00_basics.ipynb",
         "generate": "00_basics.ipynb",
         "get_obs": "00_basics.ipynb",
         "CommonCauses.initialize": "00_basics.ipynb",
         "CommonCauses.generate": "00_basics.ipynb",
         "CommonCauses.get_obs": "00_basics.ipynb",
         "Instruments.initialize": "00_basics.ipynb",
         "Instruments.get_obs": "00_basics.ipynb",
         "Instruments.generate": "00_basics.ipynb",
         "EffectModifiers.initialize": "00_basics.ipynb",
         "EffectModifiers.get_obs": "00_basics.ipynb",
         "EffectModifiers.generate": "00_basics.ipynb",
         "stochastically_convert_to_binary": "00_basics.ipynb",
         "Treatments.initialize": "00_basics.ipynb",
         "Treatments.generate": "00_basics.ipynb",
         "Treatments.get_obs": "00_basics.ipynb",
         "Outcomes": "00_basics.ipynb",
         "plot_target_vs_rest": "00_basics.ipynb",
         "plot_var_hists": "00_basics.ipynb",
         "show_correlations": "00_basics.ipynb",
         "get_Xy": "00_basics.ipynb",
         "get_model_feel": "00_basics.ipynb",
         "get_feature_importance": "00_basics.ipynb",
         "get_partial_dependencies": "00_basics.ipynb",
         "plot_partial_dependencies": "00_basics.ipynb",
         "GraphGenerator": "00_basics.ipynb",
         "get_only_Xi_to_Y": "00_basics.ipynb",
         "GraphGenerator.get_only_Xi_to_Y": "00_basics.ipynb",
         "get_Xi_to_Y_with_ccs_and_such": "00_basics.ipynb",
         "GraphGenerator.get_Xi_to_Y_with_ccs_and_such": "00_basics.ipynb",
         "vis_g": "00_basics.ipynb",
         "GraphGenerator.vis_g": "00_basics.ipynb",
         "get_gml": "00_basics.ipynb",
         "GraphGenerator.get_gml": "00_basics.ipynb"}

modules = ["basics.py"]

doc_url = "https://fastai.github.io/bcg/"

git_url = "https://github.com/fastai/bcg/tree/master/"

def custom_doc_links(name): return None
